### PR TITLE
unmask event for middle button

### PR DESCRIPTION
**Pull request by stsp**
This should allow middle button to work.

### CODE REVIEW

**Comment by jschwartzenberg** [comment]
Nice, it works indeed!

**Comment by stsp** [comment]
In what way?
I've never seen the 3rd button under win.
How to test?

**Comment by jschwartzenberg** [comment]
Check this driver zip file: http://www.driverguide.com/driver/detail.php?driverid=136392
It contains a tool called WinMouse which allows you to assign a function to the middle mouse button, such as opening the task manager. This started to work for the first time now.

**Comment by stsp** [comment]
I have problems downloading this.
It offers to download some driveragent.exe
Could you please upload?

**Comment by jschwartzenberg** [comment]
They indeed changed the site, I couldn't get it there anymore either. I still had the zipfile though, here it is: [ws-9.zip](https://github.com/jschwartzenberg/win31-mouse-driver/files/412002/ws-9.zip)

**Comment by stsp** [comment]
Wow! Works.
Basically it seems the right button is unused
either, unless you bind it with that program.

**Comment by jschwartzenberg** [comment]
But the right button you could at least test with the normal control panel ;)
I would expect at least webbrowsers to support it with a context menu.

**Comment by stsp** [comment]
You can try netscape gold.

**Comment by stsp** [comment]
I wonder if the right button will work as
expected in netscape, after bound to something
else by that prog.

**Pull request merged**
